import React, { useState, useContext, useEffect } from "react";
import { AuthContext } from "../../context/AuthContext";
import { db } from "../../services/firebase";
import {
    collection,
    query,
    where,
    getDocs,
    doc,
    getDoc,
    Timestamp,
} from "firebase/firestore";
import Button from "../../components/Button";
import {
    FiFileText,
    FiDownload,
    FiCalendar,
    FiCheckCircle,
} from "react-icons/fi";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const Statement = () => {
    const { user } = useContext(AuthContext);
    const [activeTab, setActiveTab] = useState("journal");
    const [startDate, setStartDate] = useState("");
    const [endDate, setEndDate] = useState("");
    const [loading, setLoading] = useState(false);
    const [friendsMap, setFriendsMap] = useState({});

    // 1. Fetch Friends
    useEffect(() => {
        const fetchFriends = async () => {
            if (user?.uid) {
                const docSnap = await getDoc(doc(db, "users", user.uid));
                if (docSnap.exists()) {
                    const list = docSnap.data().friendsList || [];
                    const map = {};
                    list.forEach((f) => (map[f.uid] = f.username));
                    setFriendsMap(map);
                }
            }
        };
        fetchFriends();
    }, [user]);

    const getName = (uid) => {
        if (uid === user.uid) return "You";
        if (uid === "SELF") return "Self";
        return friendsMap[uid] || "Unknown User";
    };

    // --- 2. GENERATE JOURNAL PDF ---
    const generateJournalPDF = async () => {
        if (!startDate || !endDate)
            return alert("Please select both start and end dates.");
        setLoading(true);

        try {
            const start = new Date(startDate);
            const end = new Date(endDate);
            end.setHours(23, 59, 59);

            const q = query(
                collection(db, "journal"),
                where("uid", "==", user.uid),
                where("date", ">=", Timestamp.fromDate(start)),
                where("date", "<=", Timestamp.fromDate(end)),
            );

            const snapshot = await getDocs(q);
            const data = snapshot.docs.map((doc) => doc.data());

            data.sort((a, b) => a.date.seconds - b.date.seconds);

            if (data.length === 0) {
                setLoading(false);
                return alert("No journal entries found for this period.");
            }

            let totalIncome = 0;
            let totalExpense = 0;

            const rows = data.map((item) => {
                const amountVal = Number(item.amount) || 0;
                if (item.type === "income") totalIncome += amountVal;
                else totalExpense += amountVal;

                return [
                    new Date(item.date.seconds * 1000).toLocaleDateString(),
                    item.description,
                    item.type.toUpperCase(),
                    item.type === "income" ? `+ ${amountVal}` : `- ${amountVal}`,
                ];
            });

            const doc = new jsPDF();
            doc.setFontSize(22);
            doc.setTextColor(33, 150, 243);
            doc.text("Journal Statement", 14, 22);

            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(`Generated by Splitter App`, 14, 28);
            doc.text(`Period: ${startDate} to ${endDate}`, 14, 34);

            autoTable(doc, {
                startY: 40,
                head: [["Date", "Description", "Type", "Amount (Rs.)"]],
                body: rows,
                theme: "grid",
                headStyles: { fillColor: [33, 150, 243] },
            });

            const finalY = doc.lastAutoTable.finalY + 10;
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(`Total Income: Rs. ${totalIncome}`, 14, finalY);
            doc.text(`Total Expense: Rs. ${totalExpense}`, 14, finalY + 6);

            const savings = totalIncome - totalExpense;
            doc.setFontSize(14);
            doc.setTextColor(savings >= 0 ? "008000" : "FF0000");
            doc.text(`Net Savings: Rs. ${savings}`, 14, finalY + 14);

            doc.save(`Journal_${startDate}_${endDate}.pdf`);
        } catch (error) {
            console.error("PDF Error:", error);
            alert("Error generating PDF.");
        }
        setLoading(false);
    };

    // --- 3. GENERATE SPLITTER PDF ---
    const generateSplitterPDF = async () => {
        if (!startDate || !endDate)
            return alert("Please select both start and end dates.");
        setLoading(true);

        try {
            const start = new Date(startDate);
            const end = new Date(endDate);
            end.setHours(23, 59, 59);

            const q1 = query(
                collection(db, "transactions"),
                where("payerId", "==", user.uid),
                where("date", ">=", Timestamp.fromDate(start)),
                where("date", "<=", Timestamp.fromDate(end)),
            );
            const q2 = query(
                collection(db, "transactions"),
                where("debtorId", "==", user.uid),
                where("date", ">=", Timestamp.fromDate(start)),
                where("date", "<=", Timestamp.fromDate(end)),
            );

            const [snap1, snap2] = await Promise.all([getDocs(q1), getDocs(q2)]);

            const allTxns = [
                ...snap1.docs.map((d) => ({ ...d.data(), role: "payer" })),
                ...snap2.docs.map((d) => ({ ...d.data(), role: "debtor" })),
            ];

            allTxns.sort((a, b) => a.date.seconds - b.date.seconds);

            if (allTxns.length === 0) {
                setLoading(false);
                return alert("No transactions found for this period.");
            }

            let totalLent = 0;
            let totalBorrowed = 0;

            const rows = allTxns.map((t) => {
                const isPersonal = t.debtorId === "SELF";
                let partyName = "Self";
                let type = "PERSONAL";
                let amountStr = `${t.amount}`;

                if (!isPersonal) {
                    if (t.role === "payer") {
                        type = "LENT";
                        partyName = getName(t.debtorId);
                        amountStr = `+ ${t.amount}`;
                        if (t.status === "confirmed") totalLent += t.amount;
                    } else {
                        type = "BORROWED";
                        partyName = getName(t.payerId);
                        amountStr = `- ${t.amount}`;
                        if (t.status === "confirmed") totalBorrowed += t.amount;
                    }
                }

                return [
                    new Date(t.date.seconds * 1000).toLocaleDateString(),
                    t.description,
                    partyName,
                    type,
                    t.status === "confirmed" ? "Confirmed" : "Pending",
                    amountStr,
                ];
            });

            const doc = new jsPDF();

            doc.setFontSize(22);
            doc.setTextColor(255, 87, 34);
            doc.text("Transaction Statement", 14, 22);

            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(`Account: ${user.email}`, 14, 28);
            doc.text(`Period: ${startDate} to ${endDate}`, 14, 34);

            autoTable(doc, {
                startY: 40,
                head: [["Date", "Desc", "Party", "Type", "Status", "Amount (Rs.)"]],
                body: rows,
                theme: "striped",
                headStyles: { fillColor: [255, 87, 34] },
            });

            const finalY = doc.lastAutoTable.finalY + 10;
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);

            doc.text(`Total Lent (Confirmed): Rs. ${totalLent}`, 14, finalY);
            doc.text(
                `Total Borrowed (Confirmed): Rs. ${totalBorrowed}`,
                14,
                finalY + 6,
            );

            doc.save(`Splitter_${startDate}_${endDate}.pdf`);
        } catch (error) {
            console.error("PDF Error:", error);
            alert("Error generating PDF.");
        }
        setLoading(false);
    };

    const handleDownload = () => {
        if (activeTab === "journal") generateJournalPDF();
        else generateSplitterPDF();
    };

    return (
        <div className="min-h-screen bg-gray-50 p-4 md:p-8 pb-24">
            <div className="max-w-2xl mx-auto">
                {/* Page Header */}
                <div className="flex items-center gap-3 mb-6 md:mb-8">
                    <div className="p-3 bg-purple-100 text-purple-600 rounded-2xl">
                        <FiFileText size={24} className="md:w-7 md:h-7" />
                    </div>
                    <div>
                        <h1 className="text-xl md:text-2xl font-bold text-gray-800">
                            Statements
                        </h1>
                        <p className="text-xs md:text-sm text-gray-500">
                            Download authentic reports
                        </p>
                    </div>
                </div>

                <div className="bg-white rounded-2xl md:rounded-3xl shadow-lg p-5 md:p-8 transition-all hover:shadow-xl">
                    {/* TABS */}
                    <div className="flex p-1 bg-gray-100 rounded-xl mb-6 md:mb-8">
                        <button
                            onClick={() => setActiveTab("journal")}
                            className={`flex-1 py-2 md:py-2.5 text-xs md:text-sm font-bold rounded-lg transition-all duration-300 ${activeTab === "journal"
                                    ? "bg-white text-blue-600 shadow-sm"
                                    : "text-gray-500 hover:text-gray-700"
                                }`}
                        >
                            Journal Report
                        </button>
                        <button
                            onClick={() => setActiveTab("splitter")}
                            className={`flex-1 py-2 md:py-2.5 text-xs md:text-sm font-bold rounded-lg transition-all duration-300 ${activeTab === "splitter"
                                    ? "bg-white text-orange-600 shadow-sm"
                                    : "text-gray-500 hover:text-gray-700"
                                }`}
                        >
                            Splitter Report
                        </button>
                    </div>

                    {/* FORM */}
                    <div className="space-y-6 animate-fade-in-up">
                        {/* Date Inputs - Fixed for Mobile */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-[10px] md:text-xs font-bold text-gray-400 uppercase mb-2">
                                    From Date
                                </label>
                                <div className="relative">
                                    <FiCalendar className="absolute left-3 top-3.5 text-gray-400" />
                                    <input
                                        type="text" // Defaults to text for placeholder
                                        placeholder="mm/dd/yyyy"
                                        onFocus={(e) => (e.target.type = "date")} // Switches to date on click
                                        onBlur={(e) => {
                                            if (!e.target.value) e.target.type = "text";
                                        }} // Switches back if empty
                                        value={startDate}
                                        onChange={(e) => setStartDate(e.target.value)}
                                        className="w-full pl-10 p-3 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:border-blue-500 transition text-sm text-gray-700"
                                    />
                                </div>
                            </div>
                            <div>
                                <label className="block text-[10px] md:text-xs font-bold text-gray-400 uppercase mb-2">
                                    To Date
                                </label>
                                <div className="relative">
                                    <FiCalendar className="absolute left-3 top-3.5 text-gray-400" />
                                    <input
                                        type="text"
                                        placeholder="mm/dd/yyyy"
                                        onFocus={(e) => (e.target.type = "date")}
                                        onBlur={(e) => {
                                            if (!e.target.value) e.target.type = "text";
                                        }}
                                        value={endDate}
                                        onChange={(e) => setEndDate(e.target.value)}
                                        className="w-full pl-10 p-3 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:border-blue-500 transition text-sm text-gray-700"
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Info Box */}
                        <div
                            className={`p-4 rounded-xl border flex items-start gap-3 ${activeTab === "journal" ? "bg-blue-50 border-blue-100 text-blue-800" : "bg-orange-50 border-orange-100 text-orange-800"}`}
                        >
                            <FiCheckCircle className="mt-0.5 shrink-0" size={18} />
                            <div>
                                <h3 className="font-bold text-sm mb-1">
                                    {activeTab === "journal"
                                        ? "Personal Journal Statement"
                                        : "Splitter Transaction Statement"}
                                </h3>
                                <p className="text-xs opacity-80 leading-relaxed">
                                    {activeTab === "journal"
                                        ? "Generates a PDF of your personal income and expense records, including totals and net savings calculations."
                                        : "Generates a detailed history of money lent and borrowed, including friend names, status, and pending requests."}
                                </p>
                            </div>
                        </div>

                        <Button
                            text={loading ? "Generating..." : "Download Statement"}
                            onClick={handleDownload}
                            disabled={loading}
                            className={`w-full py-3.5 md:py-4 text-white shadow-lg flex justify-center items-center gap-2 transform active:scale-95 transition-all text-sm md:text-base ${activeTab === "journal"
                                    ? "bg-blue-600 hover:bg-blue-700 shadow-blue-200"
                                    : "bg-orange-600 hover:bg-orange-700 shadow-orange-200"
                                }`}
                        >
                            <FiDownload className="w-4 h-4 md:w-5 md:h-5" />
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Statement;
