import { useState, useContext, useEffect } from 'react';
import { AuthContext } from '../../context/AuthContext';
import { db } from '../../services/firebase';
import {
    collection,
    query,
    where,
    getDocs,
    doc,
    getDoc,
    Timestamp,
} from 'firebase/firestore';
import {
    FiFileText,
    FiDownload,
    FiCalendar,
    FiCheckCircle,
} from 'react-icons/fi';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import Card from '../../components/Card';
import Button from '../../components/Button';
import Input from '../../components/Input';
import PageHeader from '../../components/PageHeader';

const Statement = () => {
    const { user } = useContext(AuthContext);
    const [activeTab, setActiveTab] = useState('journal');
    const [startDate, setStartDate] = useState('');
    const [endDate, setEndDate] = useState('');
    const [loading, setLoading] = useState(false);
    const [friendsMap, setFriendsMap] = useState({});

    useEffect(() => {
        const fetchFriends = async () => {
            if (user?.uid) {
                const docSnap = await getDoc(doc(db, 'users', user.uid));
                if (docSnap.exists()) {
                    const list = docSnap.data().friendsList || [];
                    const map = {};
                    list.forEach((f) => (map[f.uid] = f.username));
                    setFriendsMap(map);
                }
            }
        };
        fetchFriends();
    }, [user]);

    const getName = (uid) => {
        if (uid === user.uid) return 'You';
        if (uid === 'SELF') return 'Self';
        return friendsMap[uid] || 'Unknown User';
    };

    const generateJournalPDF = async () => {
        if (!startDate || !endDate) return alert('Please select both start and end dates.');
        setLoading(true);

        try {
            const start = new Date(startDate);
            const end = new Date(endDate);
            end.setHours(23, 59, 59);

            const q = query(
                collection(db, 'journal'),
                where('uid', '==', user.uid),
                where('date', '>=', Timestamp.fromDate(start)),
                where('date', '<=', Timestamp.fromDate(end))
            );

            const snapshot = await getDocs(q);
            const data = snapshot.docs.map((doc) => doc.data());
            data.sort((a, b) => a.date.seconds - b.date.seconds);

            if (data.length === 0) {
                setLoading(false);
                return alert('No journal entries found for this period.');
            }

            let totalIncome = 0;
            let totalExpense = 0;

            const rows = data.map((item) => {
                const amountVal = Number(item.amount) || 0;
                if (item.type === 'income') totalIncome += amountVal;
                else totalExpense += amountVal;

                return [
                    new Date(item.date.seconds * 1000).toLocaleDateString(),
                    item.description,
                    item.type.toUpperCase(),
                    item.type === 'income' ? `+ ${amountVal}` : `- ${amountVal}`,
                ];
            });

            const pdfDoc = new jsPDF();
            pdfDoc.setFontSize(22);
            pdfDoc.setTextColor(33, 150, 243);
            pdfDoc.text('Journal Statement', 14, 22);
            pdfDoc.setFontSize(10);
            pdfDoc.setTextColor(100);
            pdfDoc.text('Generated by Splitter App', 14, 28);
            pdfDoc.text(`Period: ${startDate} to ${endDate}`, 14, 34);

            autoTable(pdfDoc, {
                startY: 40,
                head: [['Date', 'Description', 'Type', 'Amount (Rs.)']],
                body: rows,
                theme: 'grid',
                headStyles: { fillColor: [33, 150, 243] },
            });

            const finalY = pdfDoc.lastAutoTable.finalY + 10;
            pdfDoc.setFontSize(12);
            pdfDoc.setTextColor(0, 0, 0);
            pdfDoc.text(`Total Income: Rs. ${totalIncome}`, 14, finalY);
            pdfDoc.text(`Total Expense: Rs. ${totalExpense}`, 14, finalY + 6);

            const savings = totalIncome - totalExpense;
            pdfDoc.setFontSize(14);
            pdfDoc.setTextColor(savings >= 0 ? '008000' : 'FF0000');
            pdfDoc.text(`Net Savings: Rs. ${savings}`, 14, finalY + 14);

            pdfDoc.save(`Journal_${startDate}_${endDate}.pdf`);
        } catch (error) {
            console.error('PDF Error:', error);
            alert('Error generating PDF.');
        }
        setLoading(false);
    };

    const generateSplitterPDF = async () => {
        if (!startDate || !endDate) return alert('Please select both start and end dates.');
        setLoading(true);

        try {
            const start = new Date(startDate);
            const end = new Date(endDate);
            end.setHours(23, 59, 59);

            const q1 = query(
                collection(db, 'transactions'),
                where('payerId', '==', user.uid),
                where('date', '>=', Timestamp.fromDate(start)),
                where('date', '<=', Timestamp.fromDate(end))
            );
            const q2 = query(
                collection(db, 'transactions'),
                where('debtorId', '==', user.uid),
                where('date', '>=', Timestamp.fromDate(start)),
                where('date', '<=', Timestamp.fromDate(end))
            );

            const [snap1, snap2] = await Promise.all([getDocs(q1), getDocs(q2)]);
            const allTxns = [
                ...snap1.docs.map((d) => ({ ...d.data(), role: 'payer' })),
                ...snap2.docs.map((d) => ({ ...d.data(), role: 'debtor' })),
            ];
            allTxns.sort((a, b) => a.date.seconds - b.date.seconds);

            if (allTxns.length === 0) {
                setLoading(false);
                return alert('No transactions found for this period.');
            }

            let totalLent = 0;
            let totalBorrowed = 0;

            const rows = allTxns.map((t) => {
                const isPersonal = t.debtorId === 'SELF';
                let partyName = 'Self';
                let type = 'PERSONAL';
                let amountStr = `${t.amount}`;

                let statusText = t.status === 'confirmed' ? 'Settled' : t.status === 'pending' ? 'Pending' : 'Unknown';

                if (!isPersonal) {
                    if (t.role === 'payer') {
                        type = 'LENT';
                        partyName = getName(t.debtorId);
                        amountStr = `+ ${t.amount}`;
                        if (t.status === 'confirmed') totalLent += Number(t.amount);
                    } else {
                        type = 'BORROWED';
                        partyName = getName(t.payerId);
                        amountStr = `- ${t.amount}`;
                        if (t.status === 'confirmed') totalBorrowed += Number(t.amount);
                    }
                }

                return [
                    new Date(t.date.seconds * 1000).toLocaleDateString(),
                    t.description,
                    partyName,
                    type,
                    statusText,
                    amountStr,
                ];
            });

            const pdfDoc = new jsPDF();
            pdfDoc.setFontSize(22);
            pdfDoc.setTextColor(255, 87, 34);
            pdfDoc.text('Transaction Statement', 14, 22);
            pdfDoc.setFontSize(10);
            pdfDoc.setTextColor(100);
            pdfDoc.text(`Account: ${user.email}`, 14, 28);
            pdfDoc.text(`Period: ${startDate} to ${endDate}`, 14, 34);

            autoTable(pdfDoc, {
                startY: 40,
                head: [['Date', 'Desc', 'Party', 'Type', 'Status', 'Amount (Rs.)']],
                body: rows,
                theme: 'striped',
                headStyles: { fillColor: [255, 87, 34] },
            });

            const finalY = pdfDoc.lastAutoTable.finalY + 10;
            pdfDoc.setFontSize(12);
            pdfDoc.setTextColor(0, 0, 0);
            pdfDoc.text(`Total Lent (Settled): Rs. ${totalLent}`, 14, finalY);
            pdfDoc.text(`Total Borrowed (Settled): Rs. ${totalBorrowed}`, 14, finalY + 6);

            pdfDoc.save(`Splitter_${startDate}_${endDate}.pdf`);
        } catch (error) {
            console.error('PDF Error:', error);
            alert('Error generating PDF.');
        }
        setLoading(false);
    };

    const handleDownload = () => {
        if (activeTab === 'journal') generateJournalPDF();
        else generateSplitterPDF();
    };

    return (
        <div className="p-4 md:p-6 pb-24 lg:pb-6">
            <PageHeader
                title="Statements"
                subtitle="Download authentic reports"
                icon={FiFileText}
                iconClassName="bg-[var(--color-primary-light)] text-[var(--color-primary)]"
            />

            <Card padding="lg" className="max-w-2xl mx-auto">
                {/* Tab Selector */}
                <div className="flex p-1 bg-[var(--color-surface-alt)] rounded-xl mb-6">
                    <button
                        onClick={() => setActiveTab('journal')}
                        className={`flex-1 py-2.5 text-xs md:text-sm font-bold rounded-lg transition-all duration-300 ${activeTab === 'journal'
                            ? 'bg-[var(--color-surface)] text-[var(--color-primary)] shadow-sm'
                            : 'text-[var(--color-text-muted)] hover:text-[var(--color-text-secondary)]'
                            }`}
                    >
                        Journal Report
                    </button>
                    <button
                        onClick={() => setActiveTab('splitter')}
                        className={`flex-1 py-2.5 text-xs md:text-sm font-bold rounded-lg transition-all duration-300 ${activeTab === 'splitter'
                            ? 'bg-[var(--color-surface)] text-[var(--color-warning)] shadow-sm'
                            : 'text-[var(--color-text-muted)] hover:text-[var(--color-text-secondary)]'
                            }`}
                    >
                        Splitter Report
                    </button>
                </div>

                <div className="space-y-5 animate-fade-in-up">
                    {/* Date Range */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <Input
                            label="From Date"
                            type="date"
                            value={startDate}
                            setValue={setStartDate}
                            icon={FiCalendar}
                        />
                        <Input
                            label="To Date"
                            type="date"
                            value={endDate}
                            setValue={setEndDate}
                            icon={FiCalendar}
                        />
                    </div>

                    {/* Info Card */}
                    <div className={`p-4 rounded-xl border flex items-start gap-3 ${activeTab === 'journal'
                        ? 'bg-[var(--color-primary-light)] border-[var(--color-primary-subtle)] text-[var(--color-primary)]'
                        : 'bg-[var(--color-warning-light)] border-[var(--color-warning)]/20 text-[var(--color-warning)]'
                        }`}>
                        <FiCheckCircle className="mt-0.5 shrink-0" size={18} />
                        <div>
                            <h3 className="font-bold text-sm mb-1">
                                {activeTab === 'journal' ? 'Personal Journal Statement' : 'Splitter Transaction Statement'}
                            </h3>
                            <p className="text-xs opacity-80 leading-relaxed">
                                {activeTab === 'journal'
                                    ? 'Generates a PDF of your personal income and expense records, including totals and net savings calculations.'
                                    : 'Generates a detailed history of money lent and borrowed, including friend names, status (Settled/Pending), and amounts.'}
                            </p>
                        </div>
                    </div>

                    {/* Download Button */}
                    <Button
                        text={loading ? 'Generating...' : 'Download Statement'}
                        onClick={handleDownload}
                        loading={loading}
                        icon={FiDownload}
                        fullWidth
                        size="lg"
                        variant="primary"
                        className={activeTab === 'splitter' ? 'bg-[var(--color-warning)] hover:opacity-90 shadow-lg shadow-amber-500/25' : ''}
                    />
                </div>
            </Card>
        </div>
    );
};

export default Statement;
